jhc_expanded_random_names.name_pool = {
    "Abel",
    "Adam Ring",
    "Adon",
    "Adrian Carmack",
    "Adrian Shephard",
    "Agent Brown",
    "Agent Jones",
    "Agent Sands",
    "Agent Smith",
    "Akuma",
    "Al Powell",
    "Albert Wesker",
    "Alec Trevelyan",
    "Alex",
    "Anarki",
    "Anton Slavik",
    "Apoc",
    "Architect",
    "Arkon",
    "Armor King",
    "Ashannar",
    "Auric Goldfinger",
    "Axel",
    "B.J. Blazkowicz",
    "Balrog",
    "Bane",
    "Baraka",
    "Barillo",
    "Barney Calhoun",
    "Baron Samedi",
    "Barry Burton",
    "Beauchamp",
    "Big Boss",
    "Big Smoke",
    "Bill Rizer",
    "Billy Clanton",
    "Billy Coen",
    "Billy Sole",
    "Birdie",
    "Bitterman",
    "Black",
    "Blade",
    "Blain Cooper",
    "Blanka",
    "Blofeld",
    "Bo' Rai Cho",
    "Bobby Prince",
    "Bombate",
    "Boris",
    "Boris Grishenko",
    "Brad Vickers",
    "Brad Whitaker",
    "Brock",
    "Browny",
    "Bruce Irvin",
    "Bryan Fury",
    "Bucho",
    "Calypso",
    "Carl Johnson",
    "Carlos Oliveira",
    "Charchian",
    "Chico",
    "Chris Redfield",
    "Chupa",
    "Claude",
    "Clutch",
    "Code Talker",
    "Cody Travers",
    "Coldman",
    "Colonel Stuart",
    "Columbo",
    "Craig Marduk",
    "Cromartie",
    "Curly Bill Brocius",
    "Cypher",
    "Cyrax",
    "Daegon",
    "Dan Hibiki",
    "Dario",
    "Dark Lord",
    "Davoth",
    "Deathshead",
    "Decoy Octopus",
    "Dee Jay",
    "Derek Yu",
    "Derrick Sund",
    "Dhalsim",
    "Dick Thornburg",
    "Dillon",
    "Dimitri Rascalov",
    "Dimitrios",
    "Ding Chavez",
    "Doc Holliday",
    "Dominic Greene",
    "Doom",
    "Dozer",
    "Dr. Julius No",
    "Dr. Magnusson",
    "Dr. Proton",
    "Drake",
    "Drebin 893",
    "Duke Nukem",
    "Dutch",
    "Dwayne Forge",
    "E. Honda",
    "Eddie Price",
    "Eddy Gordo",
    "El Mariachi",
    "Eli Vance",
    "Elliot Carver",
    "Emilio Largo",
    "Enforcer",
    "English Bob",
    "Eol Armok",
    "Ermac",
    "Ethan Winters",
    "Father Grigori",
    "Fei Long",
    "Felix Leiter",
    "Feng Wei",
    "Fergus Reid",
    "Flynn Taggart",
    "Forest Law",
    "Francisco Sanchez",
    "Frank Jaeger",
    "Frank McLaury",
    "Franklin Clinton",
    "Franz Oberhauser",
    "Frost",
    "Fujin",
    "G-Man",
    "General Carville",
    "General Graves",
    "General Solomon",
    "Georgi Koskov",
    "Geras",
    "Ghost",
    "Gill",
    "Gobinda",
    "Gordon Freeman",
    "Gorge",
    "Goro",
    "Gouken",
    "Grav",
    "Grey",
    "Grimm",
    "Guile",
    "Gun Jack",
    "Gustav Graves",
    "Guy",
    "Hannibal King",
    "Hans Gruber",
    "Havik",
    "Heihachi Mishima",
    "Henry Gupta",
    "Henry Stamper",
    "Hinx",
    "Holoduke",
    "Homer Johnston",
    "Hsu Hao",
    "Huey Emmerich",
    "Hugo Drax",
    "HUNK",
    "Hwoarang",
    "Ian McTaggart",
    "Igor Savin",
    "Ike Clanton",
    "Ilya Bely",
    "Isaac Kleiner",
    "Jack Howitzer",
    "Jack Krauser",
    "Jack Wade",
    "Jacob Orine",
    "Jake Muller",
    "James Bond",
    "Janus",
    "Jaws",
    "Jax Briggs",
    "Jin Kazama",
    "Jinpachi Mishima",
    "John Clark",
    "John Connor",
    "John McClane",
    "John Romero",
    "Johnny Cage",
    "Johnny Klebitz",
    "Johnny Ringo",
    "Joseph Hewitt",
    "Kabal",
    "Kai",
    "Kamal Khan",
    "Kananga",
    "Kane",
    "Kano",
    "Karl",
    "Kazuhira Miller",
    "Kazuya Mishima",
    "Keel",
    "Ken Masters",
    "Ken Rosenberg",
    "Kenshi",
    "Kerim Bey",
    "Khan Maykr",
    "Kincade",
    "King",
    "Klesk",
    "Kollector",
    "Kotal Kahn",
    "Kronsteen",
    "Kung Jin",
    "Kung Lao",
    "Kyle Reese",
    "Lamar Davis",
    "Lance Bean",
    "Lars Alexandersson",
    "Lazlow",
    "Le Chiffre",
    "Lee Chaolan",
    "Lei Wulong",
    "Leon Kennedy",
    "Lester Crest",
    "Link",
    "Liquid Ocelot",
    "Liquid Snake",
    "Little Bill Daggett",
    "Little Jacob",
    "Liu Kang",
    "Locke",
    "Locque",
    "Luis Sera",
    "Lyutsifer Safin",
    "M. Bison",
    "Mac Eliot",
    "Mad Dog",
    "Makron",
    "Malcolm",
    "Maligog",
    "Mallory",
    "Marc-Ange Draco",
    "Marcus Wright",
    "Marquez",
    "Marshall Law",
    "Master Miller",
    "Material Defender",
    "Matrix",
    "Matthew Kane",
    "Max Hass",
    "Mendoza",
    "Michael De Santa",
    "Mike Harrigan",
    "Mikhail Faustin",
    "Miles Dyson",
    "Minion",
    "Mishkin",
    "Mollaka",
    "Moog",
    "Morgan Earp",
    "Morpheus",
    "Morzeny",
    "Motaro",
    "Mouse",
    "Mr. Kidd",
    "Mr. White",
    "Mr. Wint",
    "Nash",
    "Ned Logan",
    "Needles Kane",
    "Neo",
    "Nick Nack",
    "Nick Parker",
    "Nicholai Ginovaef",
    "Nightwolf",
    "Niko Bellic",
    "Nilox",
    "Nils Bloodaxe",
    "No-Face",
    "Noob Saibot",
    "Novik",
    "Oddjob",
    "Odessa Cubbage",
    "Onaga",
    "Orbb",
    "Orlov",
    "Otacon",
    "Othello",
    "Ourumov",
    "Paul Bellow",
    "Paul Phoenix",
    "Phobos",
    "Phwop",
    "Piers Nivans",
    "Playboy X",
    "Poncho",
    "Preacher",
    "Premier Romanov",
    "Psycho Mantis",
    "Pushkin",
    "Quan Chi",
    "Quinn",
    "Rahul Chandra",
    "Raiden",
    "Rain",
    "Ranak",
    "Ranger",
    "Raoul Silva",
    "Raven",
    "Reaper",
    "Red Grant",
    "Reiko",
    "Reinhardt",
    "Renard",
    "Reptile",
    "Revolver Ocelot",
    "Richard Aiken",
    "Riker",
    "Roger",
    "Rolento",
    "Roman Bellic",
    "Ryder",
    "Ryu",
    "Sagat",
    "Salvatore Leone",
    "Samuel Hayden",
    "Sandy Peterson",
    "Sarge",
    "Scalebearer",
    "Scaramanga",
    "Schofield Kid",
    "Scorpion",
    "Scud",
    "Sean",
    "Sektor",
    "Seraph",
    "Sergei Dragunov",
    "Set Roth",
    "Seth",
    "Shao Kahn",
    "Sherman McMasters",
    "Shinnok",
    "Shujinko",
    "Simon Gruber",
    "Skull Face",
    "Skynet",
    "Smoke",
    "Sodom",
    "Sokolov",
    "Solid Snake",
    "Solidus Snake",
    "Sorlag",
    "Stephen Ward",
    "Steve Fox",
    "Steve Haines",
    "Stryker",
    "Sub-Zero",
    "Sully",
    "Super Spesh",
    "T-1000",
    "T-800",
    "T. Hawk",
    "Takashi Takeda",
    "Tank",
    "Tank Jr.",
    "Tanner",
    "Taven",
    "Tee Hee",
    "Tenpenny",
    "Texas Jack Vermillion",
    "Theo",
    "Thomas Parasiuk",
    "Tiger Tanaka",
    "Tim Noonan",
    "Timo Viitanen",
    "Tom McLaury",
    "Tommy Vercetti",
    "Tratos",
    "Trevor Philips",
    "Turkey Creek Jack Johnson",
    "Uriel",
    "Urien",
    "VEGA",
    "Valen",
    "Valentin Zukovsky",
    "Vamp",
    "Vega",
    "Venom Snake",
    "Victor Vance",
    "Viktor",
    "Virgil Earp",
    "Visor",
    "Volgin",
    "Volkov",
    "Vulcan Raven",
    "Wallace Breen",
    "Whistler",
    "William Munny",
    "Wrack",
    "Wyatt",
    "Wyatt Earp",
    "Xaero",
    "Xan Kriegor",
    "Yang",
    "Yoshimitsu",
    "Yun",
    "Yuri",
    "Zalminen",
    "Zangief",
    "Zao",
    "Zero",
    "Zeus Carver",
    "Zorin",
}
